// <auto-generated />
using Ds.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ds.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128144948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Ds.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active_key_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("ActiveKeyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Sydney_Roberts4@hotmail.com"
                        });
                });

            modelBuilder.Entity("Ds.Core.Entities.CustomerKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("encrypted_private_key");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("iv");

                    b.Property<byte[]>("PrivateKeySalt")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("private_key_salt");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("public_key");

                    b.Property<long?>("SupersededAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("superseded_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_keys");
                });

            modelBuilder.Entity("Ds.Core.Entities.TradeRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<string>("MetadataRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<byte[]>("Signature")
                        .HasColumnType("BLOB")
                        .HasColumnName("signature");

                    b.Property<int>("SignedAction")
                        .HasColumnType("INTEGER")
                        .HasColumnName("signed_action");

                    b.Property<long?>("SignedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("signed_at");

                    b.Property<int?>("SigningKeyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("signing_key_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SigningKeyId");

                    b.ToTable("trade_recommendations");
                });

            modelBuilder.Entity("Ds.Core.Entities.Customer", b =>
                {
                    b.HasOne("Ds.Core.Entities.CustomerKey", "ActiveKey")
                        .WithMany()
                        .HasForeignKey("ActiveKeyId");

                    b.Navigation("ActiveKey");
                });

            modelBuilder.Entity("Ds.Core.Entities.CustomerKey", b =>
                {
                    b.HasOne("Ds.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ds.Core.Entities.TradeRecommendation", b =>
                {
                    b.HasOne("Ds.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ds.Core.Entities.CustomerKey", "SigningKey")
                        .WithMany()
                        .HasForeignKey("SigningKeyId");

                    b.Navigation("Customer");

                    b.Navigation("SigningKey");
                });
#pragma warning restore 612, 618
        }
    }
}
